services:
  clients-api:
    image: ${DOCKER_REGISTRY-}clientsapi
    build:
      context: .
      dockerfile: Client/clients-api/Dockerfile
    ports:
      - "5100:5100"
      - "5002:5002"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=sqlserver-datamigration;Database=Clients;User=sa;Password=Your_password123!;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sqlserver
 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-datamigration
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "Your_password123!"
      ACCEPT_EULA: "Y"
    networks:
      - backend

networks:
  backend:
    driver: bridge